#!/usr/bin/env bash
#
# Fuzzy find a project folder, creates a new Tmux session, and attaches to it.

set -ou pipefail

cd ~/.password-store && pass git pull  &> /dev/null

export FZF_DEFAULT_OPTS='
     --height 100%
     --layout=reverse
     --inline-info
     --color=fg:#e5e9f0,hl:#81a1c1
     --color=fg+:#e5e9f0,bg+:#3b4252,hl+:#81a1c1
     --color=info:#eacb8a,prompt:#bf6069,pointer:#b48dac
     --color=marker:#a3be8b,spinner:#b48dac,header:#a3be8b'

key=$(fd . ~/.password-store --type f -e gpg | sed -E 's/.*\.password-store\/(.*)\.gpg/\1/g' | fzf)
pass show -c $key
