name: lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check nvim/
